export interface Quote {
  text: string;
  author: string;
}

export const quotes: Quote[] = [
  // Enero
  { text: "La vida no examinada no vale la pena ser vivida.", author: "Sócrates" },
  { text: "El sufrimiento es el maestro más eficaz; nadie aprende nada de la felicidad.", author: "Heródoto" },
  { text: "No somos seres humanos viviendo una experiencia espiritual, somos seres espirituales viviendo una experiencia humana.", author: "Pierre Teilhard de Chardin" },
  { text: "El hombre que mueve montañas empieza apartando piedras pequeñas.", author: "Confucio" },
  { text: "La soledad es el precio de la libertad.", author: "Arthur Schopenhauer" },
  { text: "Conócete a ti mismo y conocerás el universo y a los dioses.", author: "Inscripción en Delfos" },
  { text: "El silencio es el santuario de la prudencia.", author: "Baltasar Gracián" },
  { text: "No hay viento favorable para el que no sabe a qué puerto se dirige.", author: "Séneca" },
  { text: "La verdad es como el sol: lo puedes apagar por un tiempo, pero no va a desaparecer.", author: "Elvis Presley" },
  { text: "El tiempo es el mejor autor; siempre encuentra un final perfecto.", author: "Charlie Chaplin" },
  { text: "Lo que niegas te somete, lo que aceptas te transforma.", author: "Carl Jung" },
  { text: "El hombre es un abismo; da vértigo mirar dentro de él.", author: "Georg Büchner" },
  { text: "La paciencia es amarga, pero sus frutos son dulces.", author: "Jean-Jacques Rousseau" },
  { text: "Quien tiene un porqué para vivir puede soportar casi cualquier cómo.", author: "Friedrich Nietzsche" },
  { text: "El pensamiento es el enemigo de la perfección.", author: "Alfred North Whitehead" },
  { text: "La verdadera medida de un hombre se ve en cómo trata a alguien que no puede hacerle ningún bien.", author: "Samuel Johnson" },
  { text: "El presente es el único momento que existe; el pasado es memoria, el futuro es imaginación.", author: "Lao Tzu" },
  { text: "No es que tengamos poco tiempo, es que perdemos mucho.", author: "Séneca" },
  { text: "La libertad no es nada más que una oportunidad para ser mejores.", author: "Albert Camus" },
  { text: "El conocimiento habla, pero la sabiduría escucha.", author: "Jimi Hendrix" },
  { text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon" },
  { text: "El que controla el pasado controla el futuro; el que controla el presente controla el pasado.", author: "George Orwell" },
  { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
  { text: "El miedo es el asesino de la mente.", author: "Frank Herbert" },
  { text: "No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.", author: "Robert Louis Stevenson" },
  { text: "La duda es el origen de la sabiduría.", author: "René Descartes" },
  { text: "El único viaje verdadero no es ir a nuevos paisajes, sino tener otros ojos.", author: "Marcel Proust" },
  { text: "La muerte de un hombre es una tragedia; la muerte de millones es una estadística.", author: "Joseph Stalin" },
  { text: "El hombre está condenado a ser libre.", author: "Jean-Paul Sartre" },
  { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama" },
  { text: "El que tiene imaginación sin instrucción tiene alas sin pies.", author: "Joseph Joubert" },

  // Febrero
  { text: "La esperanza es el sueño del hombre despierto.", author: "Aristóteles" },
  { text: "El hombre sabio no se aflige por lo que no tiene, sino que se regocija por lo que tiene.", author: "Epicteto" },
  { text: "La vida comienza donde termina el miedo.", author: "Osho" },
  { text: "El mayor enemigo del conocimiento no es la ignorancia, es la ilusión del conocimiento.", author: "Stephen Hawking" },
  { text: "No hay camino hacia la paz, la paz es el camino.", author: "Mahatma Gandhi" },
  { text: "El universo no está obligado a tener sentido para ti.", author: "Neil deGrasse Tyson" },
  { text: "La memoria es el diario que todos llevamos con nosotros.", author: "Oscar Wilde" },
  { text: "El que tiene paciencia obtendrá lo que desea.", author: "Benjamin Franklin" },
  { text: "La verdad es tan valiosa que a menudo va acompañada de una escolta de mentiras.", author: "Winston Churchill" },
  { text: "El hombre es la única criatura que se niega a ser lo que es.", author: "Albert Camus" },
  { text: "La belleza perece en la vida, pero es inmortal en el arte.", author: "Leonardo da Vinci" },
  { text: "El tiempo que disfrutas perdiendo no es tiempo perdido.", author: "Bertrand Russell" },
  { text: "La locura es hacer lo mismo una y otra vez esperando resultados diferentes.", author: "Atribuido a Einstein" },
  { text: "El hombre nace libre, pero en todas partes está encadenado.", author: "Jean-Jacques Rousseau" },
  { text: "La naturaleza no hace nada en vano.", author: "Aristóteles" },
  { text: "El arte es la mentira que nos permite comprender la verdad.", author: "Pablo Picasso" },
  { text: "La venganza es un plato que se sirve frío.", author: "Proverbio antiguo" },
  { text: "El silencio es un argumento llevado a cabo por otros medios.", author: "Ernesto Che Guevara" },
  { text: "La fortuna favorece a los audaces.", author: "Virgilio" },
  { text: "El hombre es el único animal que tropieza dos veces con la misma piedra.", author: "Proverbio" },
  { text: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", author: "Nelson Mandela" },
  { text: "El dolor es inevitable, el sufrimiento es opcional.", author: "Haruki Murakami" },
  { text: "La vida es un proceso de llegar a ser, una combinación de estados que tenemos que atravesar.", author: "Anaïs Nin" },
  { text: "El único modo de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
  { text: "La mente es su propio lugar y en sí misma puede hacer un cielo del infierno, un infierno del cielo.", author: "John Milton" },
  { text: "El éxito es la capacidad de ir de fracaso en fracaso sin perder el entusiasmo.", author: "Winston Churchill" },
  { text: "La vida es demasiado importante para tomársela en serio.", author: "Oscar Wilde" },
  { text: "El cambio es la ley de la vida. Y aquellos que miran solo al pasado o al presente, seguramente se perderán el futuro.", author: "John F. Kennedy" },

  // Marzo
  { text: "La verdadera ignorancia no es la ausencia de conocimientos, sino el hecho de negarse a adquirirlos.", author: "Karl Popper" },
  { text: "El mayor peligro para la mayoría de nosotros no es que nuestra meta sea demasiado alta y no la alcancemos, sino que sea demasiado baja y la logremos.", author: "Miguel Ángel" },
  { text: "La realidad es simplemente una ilusión, aunque una muy persistente.", author: "Albert Einstein" },
  { text: "El hombre que ha empezado a vivir más seriamente por dentro, empieza a vivir más sencillamente por fuera.", author: "Ernest Hemingway" },
  { text: "La compasión es la base de toda moralidad.", author: "Arthur Schopenhauer" },
  { text: "El destino baraja las cartas, pero nosotros las jugamos.", author: "Arthur Schopenhauer" },
  { text: "La única cosa que sabemos es que no sabemos nada.", author: "Sócrates" },
  { text: "El mundo es un libro, y quienes no viajan leen solo una página.", author: "San Agustín" },
  { text: "La oscuridad no puede expulsar a la oscuridad; solo la luz puede hacer eso.", author: "Martin Luther King Jr." },
  { text: "El hombre es un animal racional que siempre pierde los estribos cuando se le pide que actúe de acuerdo con los dictados de la razón.", author: "Oscar Wilde" },
  { text: "La vida es corta, el arte largo, la oportunidad fugaz, la experiencia engañosa, el juicio difícil.", author: "Hipócrates" },
  { text: "El amor es la única fuerza capaz de transformar a un enemigo en amigo.", author: "Martin Luther King Jr." },
  { text: "La mayor gloria no es nunca caer, sino levantarse siempre.", author: "Confucio" },
  { text: "El hombre más poderoso es el que es dueño de sí mismo.", author: "Séneca" },
  { text: "La verdad es raramente pura y nunca simple.", author: "Oscar Wilde" },
  { text: "El genio es un uno por ciento de inspiración y un noventa y nueve por ciento de transpiración.", author: "Thomas Edison" },
  { text: "La mejor manera de predecir el futuro es crearlo.", author: "Peter Drucker" },
  { text: "El que no valora la vida no se la merece.", author: "Leonardo da Vinci" },
  { text: "La humildad es la base de todas las virtudes.", author: "Confucio" },
  { text: "El coraje no es la ausencia de miedo, sino el juicio de que algo es más importante que el miedo.", author: "Ambrose Redmoon" },
  { text: "La vida es lo que hacemos de ella. Los viajes son los viajeros. Lo que vemos no es lo que vemos, sino lo que somos.", author: "Fernando Pessoa" },
  { text: "El tiempo pone a cada uno en su lugar.", author: "Proverbio" },
  { text: "La imaginación es más importante que el conocimiento.", author: "Albert Einstein" },
  { text: "El que no arriesga no gana.", author: "Proverbio" },
  { text: "La diferencia entre lo que hacemos y lo que somos capaces de hacer bastaría para resolver la mayoría de los problemas del mundo.", author: "Mahatma Gandhi" },
  { text: "El secreto de la felicidad no es hacer siempre lo que se quiere, sino querer siempre lo que se hace.", author: "León Tolstói" },
  { text: "La mente que se abre a una nueva idea jamás volverá a su tamaño original.", author: "Albert Einstein" },
  { text: "El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el coraje para continuar.", author: "Winston Churchill" },
  { text: "La perfección no es alcanzable, pero si perseguimos la perfección podemos alcanzar la excelencia.", author: "Vince Lombardi" },
  { text: "El hombre sufre más por lo que imagina que por lo que realmente sucede.", author: "Séneca" },
  { text: "La vida es realmente simple, pero insistimos en hacerla complicada.", author: "Confucio" },

  // Abril
  { text: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", author: "Mahatma Gandhi" },
  { text: "El alma que puede hablar con los ojos, también puede besar con la mirada.", author: "Gustavo Adolfo Bécquer" },
  { text: "La medida del amor es amar sin medida.", author: "San Agustín" },
  { text: "El hombre absurdo es el que no cambia nunca.", author: "Auguste Barthelemy" },
  { text: "La palabra progreso no tiene ningún sentido mientras haya niños infelices.", author: "Albert Einstein" },
  { text: "El mundo está lleno de pequeñas alegrías; el arte consiste en saber distinguirlas.", author: "Li Tai-po" },
  { text: "La gratitud es no solo la más grande de las virtudes, sino la madre de todas las demás.", author: "Cicerón" },
  { text: "El hombre no es más que lo que la educación hace de él.", author: "Immanuel Kant" },
  { text: "La vida es una serie de colisiones con el futuro; no es una suma de lo que hemos sido, sino de lo que anhelamos ser.", author: "José Ortega y Gasset" },
  { text: "El perdón es la fragancia que derrama la violeta en el talón que la aplasta.", author: "Mark Twain" },
  { text: "La alegría está en la lucha, en el esfuerzo, en el sufrimiento que supone la lucha, y no en la victoria misma.", author: "Mahatma Gandhi" },
  { text: "El hombre es un dios cuando sueña y un mendigo cuando piensa.", author: "Friedrich Hölderlin" },
  { text: "La verdadera amistad es como la fosforescencia, resplandece mejor cuando todo se ha oscurecido.", author: "Rabindranath Tagore" },
  { text: "El que tiene fe en sí mismo no necesita que los demás crean en él.", author: "Miguel de Unamuno" },
  { text: "La vida es un misterio que hay que vivir, no un problema que hay que resolver.", author: "Mahatma Gandhi" },
  { text: "El silencio es el elemento en el que se forman las grandes cosas.", author: "Thomas Carlyle" },
  { text: "La soledad es necesaria para gozar de la propia compañía.", author: "Luis Buñuel" },
  { text: "El optimista ve oportunidad en cada peligro; el pesimista ve peligro en cada oportunidad.", author: "Winston Churchill" },
  { text: "La vida no se mide por las veces que respiras, sino por los momentos que te dejan sin aliento.", author: "Maya Angelou" },
  { text: "El hombre que hace más de lo que le pagan pronto será pagado por más de lo que hace.", author: "Napoleon Hill" },
  { text: "La experiencia es simplemente el nombre que le damos a nuestros errores.", author: "Oscar Wilde" },
  { text: "El que busca la verdad corre el riesgo de encontrarla.", author: "Manuel Vicent" },
  { text: "La voluntad es el verdadero origen de todo lo que hacemos.", author: "Arthur Schopenhauer" },
  { text: "El arte de vivir consiste en conservar la alegría, como se conserva la salud.", author: "Epicteto" },
  { text: "La risa es el sol que ahuyenta el invierno del rostro humano.", author: "Victor Hugo" },
  { text: "El que quiere hacer algo encuentra un medio; el que no quiere hacer nada encuentra una excusa.", author: "Proverbio árabe" },
  { text: "La pobreza no viene por la disminución de las riquezas, sino por la multiplicación de los deseos.", author: "Platón" },
  { text: "El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.", author: "Aristóteles" },
  { text: "La naturaleza hace grandes obras sin esperar recompensa alguna.", author: "Aleksandr Herzen" },
  { text: "El tiempo que pierdes quejándote lo puedes invertir mejorando.", author: "Proverbio" },

  // Mayo
  { text: "La única forma de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
  { text: "El hombre que se levanta es aún más grande que el que no ha caído.", author: "Concepción Arenal" },
  { text: "La fe mueve montañas, pero la duda las escala.", author: "E.B. White" },
  { text: "El conocimiento es poder.", author: "Francis Bacon" },
  { text: "La libertad es la posibilidad de dudar, de equivocarse, de buscar y de experimentar.", author: "Federico Fellini" },
  { text: "El hombre inteligente no es el que tiene muchas ideas, sino el que sabe sacar provecho de las pocas que tiene.", author: "Martín Descalzo" },
  { text: "La sabiduría comienza en la reflexión.", author: "Sócrates" },
  { text: "El mayor error que puedes cometer en la vida es tener continuamente miedo de cometer uno.", author: "Elbert Hubbard" },
  { text: "La vida es aquello que te pasa mientras estás ocupado haciendo otros planes.", author: "Allen Saunders" },
  { text: "El hombre se descubre cuando se mide con un obstáculo.", author: "Antoine de Saint-Exupéry" },
  { text: "La curiosidad es la mecha en la vela del aprendizaje.", author: "William Arthur Ward" },
  { text: "El camino hacia el éxito está siempre en construcción.", author: "Lily Tomlin" },
  { text: "La vida es como montar en bicicleta. Para mantener el equilibrio, debes seguir adelante.", author: "Albert Einstein" },
  { text: "El hombre que no lee buenos libros no tiene ventaja sobre el que no sabe leer.", author: "Mark Twain" },
  { text: "La adversidad hace sabios.", author: "Proverbio" },
  { text: "El precio de la grandeza es la responsabilidad.", author: "Winston Churchill" },
  { text: "La pasión es energía. Siente el poder que viene de enfocarte en lo que te emociona.", author: "Oprah Winfrey" },
  { text: "El único lugar donde el éxito viene antes que el trabajo es en el diccionario.", author: "Vidal Sassoon" },
  { text: "La confianza en sí mismo es el primer secreto del éxito.", author: "Ralph Waldo Emerson" },
  { text: "El hombre superior es modesto en su discurso pero excede en sus acciones.", author: "Confucio" },
  { text: "La creatividad es la inteligencia divirtiéndose.", author: "Albert Einstein" },
  { text: "El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez de forma más inteligente.", author: "Henry Ford" },
  { text: "La mente es como un paracaídas: solo funciona si se abre.", author: "Albert Einstein" },
  { text: "El hombre que tiene miedo sin peligro, inventa el peligro para justificar su miedo.", author: "Alain" },
  { text: "La dificultad no debe ser una excusa para la postergación.", author: "Séneca" },
  { text: "El progreso es imposible sin cambio, y aquellos que no pueden cambiar sus mentes no pueden cambiar nada.", author: "George Bernard Shaw" },
  { text: "La vida no se trata de encontrarte a ti mismo, se trata de crearte a ti mismo.", author: "George Bernard Shaw" },
  { text: "El secreto del humor es la sorpresa.", author: "Aristóteles" },
  { text: "La mejor venganza es un éxito masivo.", author: "Frank Sinatra" },
  { text: "El que tiene salud tiene esperanza; y el que tiene esperanza lo tiene todo.", author: "Proverbio árabe" },
  { text: "La única diferencia entre los santos y los pecadores es que todo santo tiene un pasado y todo pecador tiene un futuro.", author: "Oscar Wilde" },

  // Junio
  { text: "La mayor declaración de amor es la que no se hace; el hombre que siente mucho, habla poco.", author: "Platón" },
  { text: "El amor es el ala que Dios ha dado al hombre para subir hasta él.", author: "Miguel Ángel" },
  { text: "La música es el lenguaje del espíritu. Abre el secreto de la vida y trae la paz.", author: "Khalil Gibran" },
  { text: "El hombre sabio querrá estar siempre con quien sea mejor que él.", author: "Platón" },
  { text: "La vida solo puede ser comprendida mirando hacia atrás, pero ha de ser vivida mirando hacia adelante.", author: "Søren Kierkegaard" },
  { text: "El poder corrompe, y el poder absoluto corrompe absolutamente.", author: "Lord Acton" },
  { text: "La moderación es el silencio del cuerpo.", author: "William Penn" },
  { text: "El odio es el placer más duradero. Los hombres aman con prisa, pero odian con calma.", author: "Lord Byron" },
  { text: "La única cosa que debemos temer es el miedo mismo.", author: "Franklin D. Roosevelt" },
  { text: "El trabajo del pensamiento se parece a la perforación de un pozo: el agua es turbia al principio, mas luego se clarifica.", author: "Proverbio chino" },
  { text: "La envidia es una declaración de inferioridad.", author: "Napoleón Bonaparte" },
  { text: "El carácter de un hombre es su destino.", author: "Heráclito" },
  { text: "La vejez empieza cuando se pierde la curiosidad.", author: "José Saramago" },
  { text: "El mejor profeta del futuro es el pasado.", author: "Lord Byron" },
  { text: "La ira es una locura de corta duración.", author: "Horacio" },
  { text: "El sentido común es el menos común de todos los sentidos.", author: "Voltaire" },
  { text: "La historia se repite, primero como tragedia, luego como farsa.", author: "Karl Marx" },
  { text: "El que es cruel con los animales se vuelve duro también en su trato con los hombres.", author: "Immanuel Kant" },
  { text: "La civilización es una carrera entre la educación y la catástrofe.", author: "H.G. Wells" },
  { text: "El hombre es el único animal que come sin tener hambre, bebe sin tener sed y habla sin tener nada que decir.", author: "Mark Twain" },
  { text: "La bondad es el único servicio que te hará rico en la pobreza.", author: "William Shakespeare" },
  { text: "El talento se desarrolla en la soledad; el carácter en el torbellino del mundo.", author: "Johann Wolfgang von Goethe" },
  { text: "La esencia de la filosofía es que un hombre debería vivir de tal manera que su felicidad dependa lo menos posible de las cosas externas.", author: "Epicteto" },
  { text: "El hombre que no tiene imaginación no tiene alas.", author: "Muhammad Ali" },
  { text: "La vida es un tejido en el que nuestras ilusiones son la trama.", author: "Joseph Joubert" },
  { text: "El genio sin educación es como la plata en la mina.", author: "Benjamin Franklin" },
  { text: "La valentía no es la ausencia de miedo, sino el triunfo sobre él.", author: "Nelson Mandela" },
  { text: "El exceso de trabajo mata más que la ociosidad.", author: "Hipócrates" },
  { text: "La tradición no es adorar las cenizas, sino mantener vivo el fuego.", author: "Gustav Mahler" },
  { text: "El verdadero amor no espera ser invitado, sino que se da a conocer por sí mismo.", author: "Oscar Wilde" },

  // Julio
  { text: "La naturaleza es el arte de Dios.", author: "Dante Alighieri" },
  { text: "El mundo no se va a destruir por los que hacen el mal, sino por los que se quedan mirando sin hacer nada.", author: "Albert Einstein" },
  { text: "La juventud es una enfermedad que se cura con los años.", author: "George Bernard Shaw" },
  { text: "El hombre superior busca en sí mismo; el hombre inferior busca en los demás.", author: "Confucio" },
  { text: "La muerte es solo el principio de la inmortalidad.", author: "Maximilien Robespierre" },
  { text: "El amor y el deseo son las alas del espíritu de las grandes hazañas.", author: "Johann Wolfgang von Goethe" },
  { text: "La inteligencia es la capacidad de adaptarse al cambio.", author: "Stephen Hawking" },
  { text: "El placer es el comienzo y el fin de vivir feliz.", author: "Epicuro" },
  { text: "La verdad es el sol de la inteligencia.", author: "Luc de Clapiers" },
  { text: "El que vive de esperanzas muere de hambre.", author: "Benjamin Franklin" },
  { text: "La mediocridad no conoce nada superior a sí misma, pero el talento reconoce instantáneamente al genio.", author: "Arthur Conan Doyle" },
  { text: "El éxito es aprender a ir de fracaso en fracaso sin desesperarse.", author: "Winston Churchill" },
  { text: "La vida es un proceso de llegar a ser, una combinación de estados que tenemos que atravesar.", author: "Anaïs Nin" },
  { text: "El hombre nunca sabe de lo que es capaz hasta que lo intenta.", author: "Charles Dickens" },
  { text: "La filosofía es el arte de vivir.", author: "Plutarco" },
  { text: "El pesimista ve dificultad en cada oportunidad. El optimista ve oportunidad en cada dificultad.", author: "Winston Churchill" },
  { text: "La sencillez es la complejidad suprema.", author: "Leonardo da Vinci" },
  { text: "El amor es la poesía de los sentidos.", author: "Honoré de Balzac" },
  { text: "La ignorancia más peligrosa es la ignorancia de aquellos que no saben que ignoran.", author: "Allan Bloom" },
  { text: "El único verdadero viaje de descubrimiento consiste no en buscar nuevos paisajes, sino en mirar con nuevos ojos.", author: "Marcel Proust" },
  { text: "La libertad significa responsabilidad. Por eso la mayoría de los hombres le tiene miedo.", author: "George Bernard Shaw" },
  { text: "El dolor que no se desahoga con lágrimas puede hacer que sean otros órganos los que lloren.", author: "Francis J. Braceland" },
  { text: "La dignidad no consiste en tener honores, sino en merecerlos.", author: "Aristóteles" },
  { text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.", author: "Albert Schweitzer" },
  { text: "La ambición es el último refugio del fracaso.", author: "Oscar Wilde" },
  { text: "El hombre que quiere hacer algo encuentra un camino; el que no quiere nada encuentra una excusa.", author: "Stephen Dolley Jr." },
  { text: "La vida es una tragedia cuando se ve de cerca, pero una comedia cuando se ve de lejos.", author: "Charlie Chaplin" },
  { text: "El que no quiere razonar es un fanático; el que no sabe razonar es un necio; y el que no se atreve a razonar es un esclavo.", author: "William Drummond" },
  { text: "La razón es el instrumento del hombre para descubrir la verdad.", author: "Baruch Spinoza" },
  { text: "El azar favorece solo a las mentes preparadas.", author: "Louis Pasteur" },
  { text: "La ciencia es el padre del conocimiento, pero la opinión engendra la ignorancia.", author: "Hipócrates" },

  // Agosto
  { text: "La vida no es esperar a que pase la tormenta, es aprender a bailar bajo la lluvia.", author: "Vivian Greene" },
  { text: "El universo es cambio; nuestra vida es lo que nuestros pensamientos hacen de ella.", author: "Marco Aurelio" },
  { text: "La paz comienza con una sonrisa.", author: "Madre Teresa" },
  { text: "El hombre que teme sufrir ya sufre de lo que teme.", author: "Michel de Montaigne" },
  { text: "La locura es repetir la misma cosa una y otra vez y esperar resultados diferentes.", author: "Rita Mae Brown" },
  { text: "El arte más difícil es el arte de vivir.", author: "John Macy" },
  { text: "La paciencia y el tiempo hacen más que la fuerza y la violencia.", author: "Jean de La Fontaine" },
  { text: "El que controla a otros puede ser poderoso, pero el que se ha dominado a sí mismo es aún más poderoso.", author: "Lao Tzu" },
  { text: "La virtud es más bella que la belleza.", author: "Sócrates" },
  { text: "El primer paso hacia la sabiduría es el silencio; el segundo, escuchar.", author: "Proverbio hebreo" },
  { text: "La vida es un viaje, no un destino.", author: "Ralph Waldo Emerson" },
  { text: "El hombre solo yerra mientras está esforzándose.", author: "Johann Wolfgang von Goethe" },
  { text: "La grandeza de un hombre se mide por la cantidad de verdad que puede tolerar.", author: "Friedrich Nietzsche" },
  { text: "El amor no tiene cura, pero es la única cura para todos los males.", author: "Leonard Cohen" },
  { text: "La única manera de tener un amigo es ser uno.", author: "Ralph Waldo Emerson" },
  { text: "El fracaso es el condimento que da sabor al éxito.", author: "Truman Capote" },
  { text: "La tolerancia es la mejor religión.", author: "Victor Hugo" },
  { text: "El tiempo que se disfruta perdiendo no es tiempo perdido.", author: "Marthe Troly-Curtin" },
  { text: "La estupidez humana es una de las pocas cosas infinitas.", author: "Albert Einstein" },
  { text: "El que busca encuentra.", author: "La Biblia" },
  { text: "La forma más elevada de la inteligencia es pensar antes de actuar.", author: "Aristóteles" },
  { text: "El hábito es el gran guía de la vida humana.", author: "David Hume" },
  { text: "La historia enseña a los hombres que la historia no les enseña nada.", author: "Mahatma Gandhi" },
  { text: "El que habla siembra; el que escucha recoge.", author: "Proverbio argentino" },
  { text: "La mejor manera de vengarse de un enemigo es no parecerse a él.", author: "Marco Aurelio" },
  { text: "El dolor es pasajero, la gloria es eterna.", author: "Proverbio latino" },
  { text: "La sinceridad es la primera virtud del mundo.", author: "Confucio" },
  { text: "El hombre es el artifice de su propio destino.", author: "Appius Claudius" },
  { text: "La conciencia es la voz del alma; las pasiones, la del cuerpo.", author: "William Shakespeare" },
  { text: "El que es valiente es libre.", author: "Séneca" },
  { text: "La fortuna ayuda a los audaces y abandona a los tímidos.", author: "Proverbio latino" },

  // Septiembre
  { text: "La más noble función de un escritor es dar testimonio, como acta notarial, del tiempo que le ha tocado vivir.", author: "Camilo José Cela" },
  { text: "El hombre es lo que cree.", author: "Anton Chejov" },
  { text: "La imaginación es el ojo del alma.", author: "Joseph Joubert" },
  { text: "El que es feliz, hará felices a los demás también.", author: "Ana Frank" },
  { text: "La ciencia sin religión está coja, y la religión sin ciencia está ciega.", author: "Albert Einstein" },
  { text: "El hombre que mueve montañas comienza cargando pequeñas piedras.", author: "Confucio" },
  { text: "La vida es breve, pero en sus breves momentos ofrece mucho.", author: "Stephen King" },
  { text: "El verdadero heroísmo está en transformar los deseos en realidades y las ideas en hechos.", author: "Alfonso Rodríguez Castelao" },
  { text: "La sabiduría no es un producto de la educación, sino del intento de adquirirla durante toda la vida.", author: "Albert Einstein" },
  { text: "El hombre más rico es aquel cuyos placeres son los más baratos.", author: "Henry David Thoreau" },
  { text: "La vida es un juego que no permite ensayos previos.", author: "Plácido Domingo" },
  { text: "El silencio es el mejor amigo que jamás te traicionará.", author: "Confucio" },
  { text: "La originalidad no consiste en decir cosas nuevas, sino en decirlas como si nunca hubiesen sido dichas por otro.", author: "Johann Wolfgang von Goethe" },
  { text: "El hombre superior es el que siempre es fiel a la esperanza.", author: "Johann Wolfgang von Goethe" },
  { text: "La vida se contrae o se expande en proporción al coraje de uno.", author: "Anaïs Nin" },
  { text: "El que no comprende una mirada tampoco comprenderá una larga explicación.", author: "Proverbio árabe" },
  { text: "La necedad siempre tiene éxito, porque tiene muchos lectores.", author: "Voltaire" },
  { text: "El genio comienza las grandes obras, pero solo el trabajo las acaba.", author: "Joseph Joubert" },
  { text: "La realidad es aquello que, cuando dejas de creer en ello, no desaparece.", author: "Philip K. Dick" },
  { text: "El que pierde dinero, pierde mucho; el que pierde un amigo, pierde más; el que pierde la fe, pierde todo.", author: "Eleanor Roosevelt" },
  { text: "La educación es el pasaporte hacia el futuro, el mañana pertenece a aquellos que se preparan para él hoy.", author: "Malcolm X" },
  { text: "El perdón es la llave maestra que abre todas las puertas.", author: "William Arthur Ward" },
  { text: "La vida es una flor cuya miel es el amor.", author: "Victor Hugo" },
  { text: "El hombre prudente no dice todo lo que piensa, pero piensa todo lo que dice.", author: "Aristóteles" },
  { text: "La persistencia es el camino del éxito.", author: "Charles Chaplin" },
  { text: "El único fracaso verdadero en la vida es no aprender de ella.", author: "Naomi Long Madgett" },
  { text: "La justicia sin fuerza es impotente; la fuerza sin justicia es tiránica.", author: "Blaise Pascal" },
  { text: "El que no tiene memoria se hace una de papel.", author: "Gabriel García Márquez" },
  { text: "La belleza es la eternidad mirándose en un espejo.", author: "Khalil Gibran" },
  { text: "El trabajo endulza la vida, pero no a todos les gustan los dulces.", author: "Victor Hugo" },

  // Octubre
  { text: "La muerte no es nada, pero vivir derrotado y sin gloria es morir todos los días.", author: "Napoleón Bonaparte" },
  { text: "El hombre se define por lo que hace con lo que hicieron de él.", author: "Jean-Paul Sartre" },
  { text: "La prueba del placer está en el recuerdo.", author: "Oscar Wilde" },
  { text: "El conocimiento es limitado. La imaginación circunda el mundo.", author: "Albert Einstein" },
  { text: "La amistad es un alma que habita en dos cuerpos; un corazón que habita en dos almas.", author: "Aristóteles" },
  { text: "El hombre no ha nacido para resolver el problema del universo, sino para averiguar dónde empieza el problema.", author: "Johann Wolfgang von Goethe" },
  { text: "La esperanza es el sueño de un hombre despierto.", author: "Aristóteles" },
  { text: "El más terrible de los sentimientos es el sentimiento de tener la esperanza perdida.", author: "Federico García Lorca" },
  { text: "La memoria es el único paraíso del cual no podemos ser expulsados.", author: "Jean Paul" },
  { text: "El hombre que quiere conocer la verdad tiene que estar dispuesto a abandonar sus mentiras favoritas.", author: "Robert Fritz" },
  { text: "La vida tiene valor solo cuando tiene algo valioso como objetivo.", author: "Georg Wilhelm Friedrich Hegel" },
  { text: "El arte de ser sabio es el arte de saber qué ignorar.", author: "William James" },
  { text: "La lengua resiste porque es blanda; los dientes ceden porque son duros.", author: "Proverbio chino" },
  { text: "El error más grande de la democracia es creer que es el mejor sistema de gobierno.", author: "Winston Churchill" },
  { text: "La medida de la inteligencia es la capacidad de cambiar.", author: "Albert Einstein" },
  { text: "El que lee mucho y anda mucho, ve mucho y sabe mucho.", author: "Miguel de Cervantes" },
  { text: "La vida es un naufragio, pero no debemos olvidar cantar en los botes salvavidas.", author: "Voltaire" },
  { text: "El único deber que tenemos con la historia es reescribirla.", author: "Oscar Wilde" },
  { text: "La vejez es un tirano que prohíbe, bajo pena de muerte, todos los placeres de la juventud.", author: "François de La Rochefoucauld" },
  { text: "El hombre más feliz es el que hace la felicidad de un mayor número de otros.", author: "Denis Diderot" },
  { text: "La ignorancia es la madre de todos los crímenes.", author: "Honoré de Balzac" },
  { text: "El tiempo es el mejor autor: siempre encuentra el final perfecto.", author: "Charles Chaplin" },
  { text: "La vanidad es el vicio favorito del diablo.", author: "John Milton" },
  { text: "El que tiene ojos ve, el que tiene cerebro comprende.", author: "Proverbio marroquí" },
  { text: "La soledad es al espíritu lo que el alimento al cuerpo.", author: "Séneca" },
  { text: "El hombre que ha empezado a vivir más seriamente por dentro empieza a vivir más sencillamente por fuera.", author: "Ernest Hemingway" },
  { text: "La experiencia es el peor maestro: da la prueba antes de enseñar la lección.", author: "Vernon Law" },
  { text: "El pensador muere, pero sus pensamientos están más allá del alcance de la destrucción.", author: "Sarvepalli Radhakrishnan" },
  { text: "La mayor parte de los hombres emplea la primera mitad de su vida en hacer miserable la segunda.", author: "Jean de La Bruyère" },
  { text: "El verdadero progreso consiste en renovarse.", author: "Alexandre Vinet" },
  { text: "La vida es un misterio para ser vivido, no un problema para ser resuelto.", author: "Soren Kierkegaard" },

  // Noviembre
  { text: "La vida es como una leyenda: no importa que sea larga, sino que esté bien narrada.", author: "Séneca" },
  { text: "El que pierde su vida por mí, la hallará.", author: "La Biblia" },
  { text: "La ironía es una tristeza que no puede llorar y sonríe.", author: "Jacinto Benavente" },
  { text: "El mejor momento para plantar un árbol fue hace veinte años. El segundo mejor momento es ahora.", author: "Proverbio chino" },
  { text: "La imaginación es el comienzo de la creación.", author: "George Bernard Shaw" },
  { text: "El que sabe que nada sabe también sabe que sabe nada.", author: "Sócrates" },
  { text: "La vida es lo que te pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon" },
  { text: "El hombre está dispuesto siempre a negar todo aquello que no comprende.", author: "Blaise Pascal" },
  { text: "La vida sin examen no vale la pena de ser vivida.", author: "Sócrates" },
  { text: "El que desprecia la vida no es digno de ella.", author: "Leonardo da Vinci" },
  { text: "La música expresa lo que no puede decirse con palabras pero no puede permanecer en silencio.", author: "Victor Hugo" },
  { text: "El amor es una fuerza más formidable que cualquier otra.", author: "Barbara de Angelis" },
  { text: "La vida sería imposible si todo se recordase.", author: "Emile Cioran" },
  { text: "El que conoce su ignorancia es sabio.", author: "Proverbio chino" },
  { text: "La conciencia es el mejor libro de moral que tenemos.", author: "Blaise Pascal" },
  { text: "El mayor misterio del mundo es que resulta comprensible.", author: "Albert Einstein" },
  { text: "La existencia precede a la esencia.", author: "Jean-Paul Sartre" },
  { text: "El hombre que está solo es más dueño de sí.", author: "Friedrich Nietzsche" },
  { text: "La voluntad de vencer es importante, pero la voluntad de prepararse es vital.", author: "Joe Paterno" },
  { text: "El arte de vencer se aprende en las derrotas.", author: "Simón Bolívar" },
  { text: "La paciencia es la más heroica de las virtudes precisamente porque carece de toda apariencia de heroísmo.", author: "Giacomo Leopardi" },
  { text: "El único misterio de la amistad es que es más profunda que el amor y más duradera.", author: "Salvador de Madariaga" },
  { text: "La diferencia entre un hombre de éxito y otros no es una falta de fuerza, ni de conocimiento, sino más bien una falta de voluntad.", author: "Vince Lombardi" },
  { text: "El que mucho habla, mucho yerra.", author: "Proverbio" },
  { text: "La religión de un hombre no vale mucho si con ella no se benefician también los animales.", author: "Mahatma Gandhi" },
  { text: "El orgullo divide a los hombres; la humildad los une.", author: "Sócrates" },
  { text: "La inspiración existe, pero tiene que encontrarte trabajando.", author: "Pablo Picasso" },
  { text: "El valor de un hombre debe medirse por lo que da, no por lo que recibe.", author: "Albert Einstein" },
  { text: "La vida es tan incierta que la felicidad debe apresurarse.", author: "Samuel Johnson" },
  { text: "El pasado es solo la entrada al futuro.", author: "Victor Hugo" },

  // Diciembre
  { text: "La verdadera felicidad consiste en hacer el bien.", author: "Aristóteles" },
  { text: "El secreto de la vida es honestidad y juego limpio. Si puedes falsificar eso, lo tienes hecho.", author: "Groucho Marx" },
  { text: "La razón es la luz y el faro de la vida.", author: "Cicerón" },
  { text: "El que hace el bien recibe el bien.", author: "Proverbio indio" },
  { text: "La vida no es la que vivimos, sino la que recordamos para contarla.", author: "Gabriel García Márquez" },
  { text: "El futuro pertenece a quienes creen en la belleza de sus sueños.", author: "Eleanor Roosevelt" },
  { text: "La crueldad, como cualquier otro vicio, no requiere ningún motivo para ejercerla.", author: "George Eliot" },
  { text: "El hombre nunca es demasiado viejo para aprender.", author: "Thomas Middleton" },
  { text: "La verdad os hará libres.", author: "La Biblia" },
  { text: "El que siembra vientos, recoge tempestades.", author: "Proverbio bíblico" },
  { text: "La bondad es el único servicio que pagará siempre el precio que ha costado.", author: "Malcolm Forbes" },
  { text: "El que vive para sí mismo está muerto para los demás.", author: "Publilius Syrus" },
  { text: "La esperanza es una cosa buena, quizá la mejor de las cosas, y las cosas buenas nunca mueren.", author: "Stephen King" },
  { text: "El hombre que confía en sí mismo gana la confianza de los demás.", author: "Proverbio judío" },
  { text: "La vida solo puede ser comprendida mirando hacia atrás; mas solo puede ser vivida mirando hacia adelante.", author: "Soren Kierkegaard" },
  { text: "El miedo a la muerte es peor que la muerte misma.", author: "Publilius Syrus" },
  { text: "La vida es un eco: lo que das, lo recibes.", author: "Proverbio chino" },
  { text: "El hombre que más ha vivido no es el que más años ha cumplido, sino aquel que más ha experimentado la vida.", author: "Jean-Jacques Rousseau" },
  { text: "La vida es un sueño del que la muerte nos despierta.", author: "Proverbio persa" },
  { text: "El que anda siempre pensando, andará tropezando.", author: "Proverbio" },
  { text: "La humildad es el primer escalón para la sabiduría.", author: "Santo Tomás de Aquino" },
  { text: "El hombre no tiene peor enemigo que él mismo.", author: "Cicerón" },
  { text: "La sabiduría nos llega cuando ya no nos sirve de nada.", author: "Gabriel García Márquez" },
  { text: "El tiempo es muy lento para los que esperan, muy rápido para los que tienen miedo.", author: "William Shakespeare" },
  { text: "La vida es corta; la muerte, segura.", author: "Proverbio latino" },
  { text: "El principio de la sabiduría es el temor del Señor.", author: "La Biblia" },
  { text: "La noche es más oscura justo antes del amanecer.", author: "Thomas Fuller" },
  { text: "El pasado no puede cambiarse. El futuro aún está en tu poder.", author: "Hugh White" },
  { text: "La mayor gloria de vivir no está en no caer nunca, sino en levantarnos cada vez que caemos.", author: "Nelson Mandela" },
  { text: "El fin es el comienzo de todas las cosas.", author: "T.S. Eliot" },
  { text: "La vida es el arte de sacar conclusiones suficientes de datos insuficientes.", author: "Samuel Butler" },
];

export function getQuoteForDay(dayOfYear: number): Quote {
  const index = (dayOfYear - 1) % quotes.length;
  return quotes[index];
}

export function getDayOfYear(date: Date = new Date()): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  return Math.floor(diff / oneDay);
}

export function formatDate(date: Date = new Date()): string {
  return date.toLocaleDateString('es-ES', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
}
